version: '3'
services:
    db: 
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        volumes:
            - ./devops/mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: silverius_codes_scheduler
            MYSQL_ROOT_PASSWORD: cde3bgt5
        ports:
            - "3306:3306"
    redis:
        image: redis:5.0.7
        ports:
            - '6379:6379'
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
        volumes: 
            - ".:/myapp"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
            - redis
        environment:
            TZ: Asia/Singapore
            DB_USER: root
            DB_NAME: silverius_codes_scheduler
            DB_PASSWORD: cde3bgt5
            DB_HOST: db
            REDIS_HOST: redis