version: '2'
services:
    db: 
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: silverius_codes_scheduler
            MYSQL_ROOT_PASSWORD: cde3bgt5
        ports:
            - "3306:3306"
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/myapp"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: silverius_codes_scheduler
            DB_PASSWORD: cde3bgt5
            DB_HOST: db
